// threads
export const FETCH_THREADS_REQUEST = 'FETCH_THREADS_REQUEST'
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS'
export const FETCH_THREADS_FAILURE = 'FETCH_THREADS_FAILURE'

export const FETCH_SINGLE_THREAD_REQUEST = 'FETCH_SINGLE_THREAD_REQUEST'
export const FETCH_SINGLE_THREAD_SUCCESS = 'FETCH_SINGLE_THREAD_SUCCESS'
export const FETCH_SINGLE_THREAD_FAILURE = 'FETCH_SINGLE_THREAD_FAILURE'

export const UPDATE_THREAD_REQUEST = 'UPDATE_THREAD_REQUEST'
export const UPDATE_THREAD_SUCCESS = 'UPDATE_THREAD_SUCCESS'
export const UPDATE_THREAD_FAILURE = 'UPDATE_THREAD_FAILURE'

export const CREATE_THREAD_REQUEST = 'CREATE_THREAD_REQUEST'
export const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS'
export const CREATE_THREAD_FAILURE = 'CREATE_THREAD_FAILURE'

export const DELETE_THREAD_REQUEST = 'DELETE_THREAD_REQUEST'
export const DELETE_THREAD_SUCCESS = 'DELETE_THREAD_SUCCESS'
export const DELETE_THREAD_FAILURE = 'DELETE_THREAD_FAILURE'

// replies TODO:
export const FETCH_REPLIES_REQUEST = 'FETCH_REPLIES'
export const FETCH_REPLIES_SUCCESS = 'FETCH_REPLIES'
export const FETCH_REPLIES_FAILURE = 'FETCH_REPLIES'

export const EDIT_REPLY_REQUEST = 'EDIT_REPLY'
export const EDIT_REPLY_SUCCESS = 'EDIT_REPLY'
export const EDIT_REPLY_FAILURE = 'EDIT_REPLY'

export const DELETE_REPLY_REQUEST = 'DELETE_REPLY'
export const DELETE_REPLY_SUCCESS = 'DELETE_REPLY'
export const DELETE_REPLY_FAILURE = 'DELETE_REPLY'

export const CREATE_REPLY_REQUEST = 'CREATE_REPLY'
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY'
export const CREATE_REPLY_FAILURE = 'CREATE_REPLY'

export const UPDATE_REPLY_REQUEST = 'UPDATE_REPLY'
export const UPDATE_REPLY_SUCCESS = 'UPDATE_REPLY'
export const UPDATE_REPLY_FAILURE = 'UPDATE_REPLY'
