// threads
export const FETCH_THREADS_REQUEST = 'FETCH_THREADS_REQUEST'
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS'
export const FETCH_THREADS_FAILURE = 'FETCH_THREADS_FAILURE'

export const UPDATE_THREAD_REQUEST = 'UPDATE_THREAD_REQUEST'
export const UPDATE_THREAD_SUCCESS = 'UPDATE_THREAD_SUCCESS'
export const UPDATE_THREAD_FAILURE = 'UPDATE_THREAD_FAILURE'

export const CREATE_THREAD_REQUEST = 'CREATE_THREAD_REQUEST'
export const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS'
export const CREATE_THREAD_FAILURE = 'CREATE_THREAD_FAILURE'

export const DELETE_THREAD_REQUEST = 'DELETE_THREAD_REQUEST'
export const DELETE_THREAD_SUCCESS = 'DELETE_THREAD_SUCCESS'
export const DELETE_THREAD_FAILURE = 'DELETE_THREAD_FAILURE'

// replies TODO:
export const FETCH_REPLIES = 'FETCH_REPLIES'

export const EDIT_REPLY = 'EDIT_REPLY'

export const DELETE_REPLY = 'DELETE_REPLY'

export const CREATE_REPLY = 'CREATE_REPLY'
